# Generated by Django 5.2.5 on 2025-09-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bari_app', '0005_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
